#!groovy

// Generated by IBM TransformationAdvisor
// Sun Mar 17 11:13:43 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}