#!groovy

// Generated by IBM TransformationAdvisor
// Sat Mar 16 15:57:16 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}